#2 Configurar test report

diff --git a/.github/workflows/build-pr-gradle.yml b/.github/workflows/build-pr-gradle.yml
--- a/.github/workflows/build-pr-gradle.yml
+++ b/.github/workflows/build-pr-gradle.yml
@@ -16,14 +16,15 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
       - name: Build with Gradle
-        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
+        run: |
+          chmod +x gradlew
+          ./gradlew build -x test
+      - name: Test with Gradle
+        run: |
+          chmod +x gradlew
+          ./gradlew test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
         with:
-          arguments: build
-      - name: Add coverage to PR
-        id: jacoco
-        uses: madrapps/jacoco-report@v1.3
-        with:
-          paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
-          token: ${{ secrets.GITHUB_TOKEN }}
-          min-coverage-overall: 40
-          min-coverage-changed-files: 60
+          report_paths: '**/build/test-results/test/TEST-*.xml'
